name: CI hello
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  CI:
    name: Publish hello app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish Hello
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: latest
          verb: call
          module: github.com/sealder/enter-the-daggerverse/hello@snowcamp-sealder
          args: publish --source=.
